{% set name = "google-cloud-bigtable" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b2fc24b4eae190c90a0f2e39bc0a147a3243ba0989290bf9f9c0cfd59dc0c3b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --verbose
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc 1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-core >=1.4.1,<3.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13dev
    - packaging >=14.3
    - proto-plus >=1.18.0

test:
  imports:
    - google.cloud.bigtable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigtable
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python Client for Google Cloud Bigtable
  description: |
    Python Client for Google Cloud Bigtable
    -------------------------

    [Google Cloud Bigtable](https://cloud.google.com/bigtable) is Google's NoSQL Big Data database service. It's the
    same database that powers many core Google services, including Search,
    Analytics, Maps, and Gmail.

    - [Client Library Documentation](https://googleapis.github.io/google-cloud-python/latest/bigtable/usage.html)
    - [Product Documentation](https://cloud.google.com/bigtable/docs)

    Quick Start
    -----------

    In order to use this library, you first need to go through the following steps:

    1. [Select or create a Cloud Platform project.](https://console.cloud.google.com/project)
    2. [Enable billing for your project.](https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project)
    3. [Enable the Cloud Bigtable API.](https://cloud.google.com/bigtable)
    4. [Setup Authentication.](https://googleapis.github.io/google-cloud-python/latest/core/auth.html)

    Supported Python Versions
    -------------------------
    Python >= 3.5

    Deprecated Python Versions
    -------------------------
    Python == 2.7. Python 2.7 support will be removed on January 1, 2020.

  doc_url: https://googleapis.dev/python/bigtable/latest/index.html
  dev_url: https://github.com/googleapis/python-bigtable

extra:
  recipe-maintainers:
    - BrentDorsey
    - xylar
