travis:
  secure:
    BINSTAR_TOKEN: mEb+AHe+KYRXOOMpQNCKh/5bhiBmDfC32T5mMRQoynNz7CDv4VEQbd3/PZAu6eEEBVIxI0yDhN1z2R39WGxqcW/wxbLFS8cCbPpqtVncDTLH5IwFK+fcQmHQNBwl3lb6CF158C6THxOEBSz1TTYWEtBEyop07csaNUwGDCtcg8NuABi/WeXmG0TVvHO09GFGLHzI2t+4owTCUE3vXFSuKN+Jsi4aCeasLR+Jk41AHvzGUcOH2XVMMSwy0kvMmcRnfxNCTb7onON6M2ENBfDnVtmL8x4AM34UVZYFe9/W/Lt0IVu8kF6tzD9sVlByMOcsNONFwEIxB3ZzXzv7TMQNDTbHbz0wzKmHQDT5jUsneZB/Bgie4nYNzLAeMA02YenGwEzdlIyxILaQTSYYn9LpeAszYBwQ2gBF83IpDtWwVNJVSqFZDBC0Z+MKEl10Wu/KnGCAgs1Ig5/ohNOeQXFJCmcNOCFamITK2KfUuIRKR77w7xzg+XbFy+jzBaBpwGVCb/qKKXXyjIfACIN+grcbaNNmoVQsvyvV90eh5VBCLcmJC3/jX1D53LA1+6VQvY0ABv1QmfctlkfC8X7y/Eu/eXuscaJCf684oOuR33P3uJNxISRru0HKluw30w5KXvywXvhVJ72tno/rPI4nKq5vANc/0Ggvc9uYabwJ5Rg2iRE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
